### ISSUE TITLE
Something wrong with rabbitmqc dependency 

### ISSUE THREAD

**Issue by ghost** [open-rnd/OLRabbitMQ#2]
After pod install project fails to build

'amqp.h' file not found with <angled> include; use "quotes" instead 
'amqp_tcp_socket.h' file not found with <angled> include; use "quotes" instead

and so on

**Comment by dlewanda-birchbox** [comment]
I'm seeing the same thing. This is with XCode 7.1 on OS X 10.11 (El Capitan)

**Comment by ciumvacTweets** [comment]
add "${PODS_ROOT}  to build settings -> header search path (works for me)

**Comment by albert0m** [comment]
experiencing the same problem and adding the ${PODS_ROOT} didn't fix it for us

**Comment by ghost** [comment]
Please try new update from https://github.com/7tomek/OLRabbitMQ -> version: bump 0.3.0 with rabbitmqc 0.6.8
